name: Deploy Later
on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  deploy:
    strategy:
      matrix:
        env: [dev, sandbox, prod]
        include:
          - env: sandbox
            other: sbx

    runs-on: ubuntu-latest
    environment: 
        name: ${{ matrix.env }}
    steps:
        - name: my-step
          run: echo "Hello ${{ matrix.other || matrix.env }}!"

